### ISSUE TITLE
life-ToDo

### ISSUE THREAD

**Issue by misakar** [UiharuOS/uiharu#3]
今后的路要自己走, 帮助能帮助的人
<hr/>

## 2016年

+ [ ] uiharuos完成

## 2017年

+ [ ] 精通Python
    - [ ] 彻底弄明白flask源码
    - [ ] 木犀PythonWeb的2个Lab设计
    - [ ] 写Pythonic的代码
    - [ ] 彻底弄明白asyncio
+ [ ] 算法
    - [ ] 读完《C++数据结构与算法》+ 所有练习
    - [ ] 读完《算法第4版》+ 所有练习
+ [ ] C++
    - [ ] 读完《C++ primary plus》 + 所有练习
    - [ ] 读完《effective C++》+ 所有练习
    - [ ] 完成C++ Web框架muxi
+ [ ] 读完《CSAPP》或者 《计算机网络》
+ [ ] 找到实习, 理想实习: 豆瓣、知乎
